<?xml version="1.0" ?>
<testsuite name="unittest.loader._FailedTest-20191130110902" tests="2" time="0.000" failures="0" errors="2">
	<testcase classname="unittest.loader._FailedTest" name="test_addbook" time="0.000">
		<error type="ImportError" message="Failed to import test module: test_addbook
Traceback (most recent call last):
  File &quot;C:\Users\Pranay Chowdary\AppData\Local\Programs\Python\Python38-32\lib\unittest\loader.py&quot;, line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File &quot;C:\Users\Pranay Chowdary\AppData\Local\Programs\Python\Python38-32\lib\unittest\loader.py&quot;, line 377, in _get_module_from_name
    __import__(name)
  File &quot;C:\Users\Pranay Chowdary\Desktop\PyMicroservices-master\Source\test_addbook.py&quot;, line 5, in &lt;module&gt;
    from addhandler import AddHandler
  File &quot;C:\Users\Pranay Chowdary\Desktop\PyMicroservices-master\Source\addhandler.py&quot;, line 1, in &lt;module&gt;
    import tornado.web
ModuleNotFoundError: No module named 'tornado'
"><![CDATA[ImportError: Failed to import test module: test_addbook
Traceback (most recent call last):
  File "C:\Users\Pranay Chowdary\AppData\Local\Programs\Python\Python38-32\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Pranay Chowdary\AppData\Local\Programs\Python\Python38-32\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\Users\Pranay Chowdary\Desktop\PyMicroservices-master\Source\test_addbook.py", line 5, in <module>
    from addhandler import AddHandler
  File "C:\Users\Pranay Chowdary\Desktop\PyMicroservices-master\Source\addhandler.py", line 1, in <module>
    import tornado.web
ModuleNotFoundError: No module named 'tornado'

]]></error>
	</testcase>
	<testcase classname="unittest.loader._FailedTest" name="test_delbook" time="0.000">
		<error type="ImportError" message="Failed to import test module: test_delbook
Traceback (most recent call last):
  File &quot;C:\Users\Pranay Chowdary\AppData\Local\Programs\Python\Python38-32\lib\unittest\loader.py&quot;, line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File &quot;C:\Users\Pranay Chowdary\AppData\Local\Programs\Python\Python38-32\lib\unittest\loader.py&quot;, line 377, in _get_module_from_name
    __import__(name)
  File &quot;C:\Users\Pranay Chowdary\Desktop\PyMicroservices-master\Source\test_delbook.py&quot;, line 5, in &lt;module&gt;
    from addhandler import AddHandler
  File &quot;C:\Users\Pranay Chowdary\Desktop\PyMicroservices-master\Source\addhandler.py&quot;, line 1, in &lt;module&gt;
    import tornado.web
ModuleNotFoundError: No module named 'tornado'
"><![CDATA[ImportError: Failed to import test module: test_delbook
Traceback (most recent call last):
  File "C:\Users\Pranay Chowdary\AppData\Local\Programs\Python\Python38-32\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Pranay Chowdary\AppData\Local\Programs\Python\Python38-32\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\Users\Pranay Chowdary\Desktop\PyMicroservices-master\Source\test_delbook.py", line 5, in <module>
    from addhandler import AddHandler
  File "C:\Users\Pranay Chowdary\Desktop\PyMicroservices-master\Source\addhandler.py", line 1, in <module>
    import tornado.web
ModuleNotFoundError: No module named 'tornado'

]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
